name: ifarmer_assignment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  #flutter sdk
  flutter:
    sdk: flutter

  #other library
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_form_builder: 10.0.1
  form_builder_validators: 11.2.0
  flutter_pdfview: ^1.3.2
  intl: ^0.20.0
  flutter_cupertino_date_picker_fork: ^1.0.7
  jwt_decode: ^0.3.1
  connectivity_plus: ^6.1.3
  fluttertoast: ^8.2.8
  google_fonts: ^4.0.5
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0-alpha.3
  package_info_plus: ^8.1.0
  device_info_plus: ^11.1.0

  percent_indicator: ^4.2.2
  date_format: ^2.0.6
  group_radio_button: ^1.2.0
  age_calculator: ^1.0.0
  dropdown_button2: ^2.3.9
  image_picker: ^0.8.0+3
  flutter_file_dialog: ^3.0.2

  permission_handler: ^11.3.1
  file_picker: 8.1.0
  flutter_image_compress: ^2.4.0
  mime: ^1.0.1
  mime_type: ^1.0.0
  share_plus: ^11.0.0
  marquee: ^2.3.0
  themed: ^7.0.0
  webview_flutter: ^4.10.0

  #bluetooth
  flutter_blue_plus: ^1.35.3

  #flutter_downloader
  flutter_downloader: 1.12.0


  open_file: ^3.5.10
  flutter_timezone: ^3.0.1
  audioplayers: ^6.1.0
  fl_chart: ^1.0.0
  input_quantity: 2.4.1
  collection: ^1.17.2
  infinite_scroll_pagination: ^5.0.0
  country_code_picker: ^3.3.0
  month_picker_dialog: ^6.2.4
  dropdown_search: ^5.0.6
  simple_animations: ^5.0.2
  get: ^4.6.6
  http: ^1.1.0
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

dependency_overrides:
  chucker_flutter: 1.8.5


flutter:
  uses-material-design: true
